### ISSUE TITLE
Animations | Content width

### ISSUE THREAD

**Issue by JSto91** [iota-community/treasury-web#15]
**Animations**

I noticed the background of the header animation(video) is not 100% white. I made a new SVG animation now (slightly different/transparent background) which i would insert.

After testing it, i noticed the animations in "How voting works" stopped. I don't know why there is a conflict but after changing the code from:

```
<svg>
....
</svg>

```
to

```
<object type="image/svg+xml" data="sample.svg">

<img src="sample.svg" />

</object>

```

it worked again.

Can i make these changes?

--

**Content width**

Is it possible to change the max-width of the content box to 1340px? 😅

**Comment by adam-635** [comment]
Can you just create PR against gh-pages2 and we will merge it in?
